// Generated by CoffeeScript 2.3.2
(function() {
  var https, req, url;

  https = require('https');

  url = 'api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=296825658cf6173062078c07ff1ab3ce';

  console.log(url);

  req = https.get(url, function(res) {
    var status, value;
    status = res.statusCode;
    value = status === 200 ? 1 : 0;
    if (status === 200) {
      // ...
      console.log("yey!");
      return res.on('data', function(chunk) {
        return console.log('body: ' + chunk);
      });
    } else {
      // ...
      return console.log("i'm not worthy");
    }
  });

  req.on('error', function() {
    var msg;
    msg = "not available";
    return console.log(msg);
  });

  console.log("done!");

}).call(this);
