// Generated by CoffeeScript 2.3.2
(function() {
  var quadratic, square;

  square = function(a) {
    return a * a;
  };

  quadratic = function(a, b, c) {
    return square(a) + 2 * a * b + c;
  };

  quadratic(2, 5, 6);

}).call(this);
