// Generated by CoffeeScript 2.3.2
(function() {
  var quadratic, square;

  square = function(a) {
    return a * a;
  };

  quadratic = function(a, b, c) {
    rez1;
    rez2;
    var d, rez1, rez2;
    d = b * b - 4 * a * c;
    console.log(d);
    if (d === 0) {
      rez1 = -1 * b / (2 * a);
      return console.log('result 1 = ', rez1);
    } else if (d > 0) {
      rez1 = (-b + Math.sqrt(d)) / (2 * a);
      rez2 = (-b - Math.sqrt(d)) / (2 * a);
      return console.log('result 1 = ', rez1, 'result 2 = ', rez2);
    } else if (d < 0) {
      return console.log('there is no answer');
    }
  };

  quadratic(1, -70, 600);

}).call(this);
