// Generated by CoffeeScript 2.3.2
(function() {
  /*
   * Draw some shapes on the console
   * Copyright (c) 2014, Robert Eisele (robert@xarg.org)
   * Dual licensed under the MIT or GPL Version 2 licenses.
   */
  var draw;

  draw = function(size, cb) {
    var chars, i, j;
    chars = [":", "O"];
    i = 0;
    while (i < size) {
      j = 0;
      while (j < size) {
        process.stdout.write(chars[Number(cb(i, j, size))]);
        j++;
      }
      process.stdout.write("\n");
      i++;
    }
    console.log("\n\n\n");
    process.stdout.prompt();
  };

  //# Draw a triangle
  draw(30, function(r, c, s) {
    return r < c;
  });

  //# Draw a circle 
  draw(30, function(r, c, s) {
    return Math.pow(r - s / 2 + 1, 2) + Math.pow(c - s / 2 + 1, 2) < Math.pow(s / 2, 2);
  });

  //# Draw a house
  draw(30, function(r, c, s) {
    return Math.abs(c - s / 2) < r;
  });

  //# Draw a card
  draw(30, function(r, c, s) {
    return Math.abs(r - s / 2) < Math.abs(c - s / 2);
  });

  //# Draw a rhombus
  draw(30, function(r, c, s) {
    var t;
    t = Math.abs(r - (s - 1) / 2);
    return (t < c && c < s - t);
  });

  //# Draw a pyramid
  draw(30, function(r, c, s) {
    return Math.abs(2 * c - s + 1) <= r;
  });

  //# Draw an umbrella
  draw(30, function(r, c, s) {
    return Math.abs(c - (s - 1) / 2) <= r && (r < (s - 1) / 2 || c === s >> 1);
  });

}).call(this);
